name: build

on:
  workflow_dispatch:
  schedule:
    - cron: "10 19 * * *"

jobs:
  build:
    name: Generate and sync docker image
    runs-on: ubuntu-18.04

    steps:
      - name: clone source code
        uses: actions/checkout@v1
      - name: Dockerhub Login
        run: |
          echo '${{ secrets.DOCKER_PASSWD }}' | docker login -u '${{ secrets.DOCKER_USERNAME }}' --password-stdin
      - name: github Repo Login
        run: |
          docker login -u '${{ secrets.DOCKER_USERNAME }}' -p '${{ secrets.GITHUB_PACKAGES_TOKEN }}' https://docker.pkg.github.com/
      - name: build and push docker image
        run: |
          export DOCKER_USERNAME=${{ secrets.DOCKER_USERNAME }}
          make -j $(nproc)
