name: build

on:
  workflow_dispatch:
  schedule:
    - cron: "10 19 * * *"

jobs:
  build:
    name: Generate and sync docker image
    runs-on: ubuntu-18.04

    steps:
      - name: clone source code
        uses: actions/checkout@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWD }}
      - name: build and push docker image
        run: |
          export DOCKER_USERNAME=${{ secrets.DOCKER_USERNAME }}
          make -j $(nproc)
