name: Generate and sync docker image

on:
  schedule:
    - cron: "10 19 * * *"

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
      - name: clone source code
        uses: actions/checkout@v1
      - name: Dockerhub Login
        uses: Azure/docker-login@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWD }}
          login-server: https://index.docker.io/v1/
      - name: github Repo Login
        uses: Azure/docker-login@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.GITHUB_PACKAGES_TOKEN }}
          login-server: https://docker.pkg.github.com/
      - name: build and push docker image
        run: |
          export DOCKER_USERNAME=${{ secrets.DOCKER_USERNAME }}
          make -j $(nproc)
