name: CI

on:
  schedule:
    - cron: "10 5 * * *"

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v1
      - name: Docker Login
        uses: Azure/docker-login@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWD }}
          login-server: https://index.docker.io/v1/
      - name: build and push docker image
        run: |
          make -j8
